# ML model

- The problem we are handling right now is called as  single-label multi-class classification problem. In this type of problem, each instance is assigned exactly one label from a set of multiple possible classes. In your case, the classes are "brain", "heart", "lung", and "kidney".

SVM and Logistic Regression cannot handle Multi-Class classification Natively, and hence we use One-vs-Rest (OvR) or One-vs-One (OvO) strategies to handle multi-class classification.

Several machine learning algorithms can handle multi-class classification natively, meaning they are designed to work directly with multiple classes without needing additional strategies like One-vs-Rest (OvR) or One-vs-One (OvO). Some examples of algorithms that support multi-class classification natively include:
- decision tree classifier >
- random forest classifier >
- Gradieent Boosting Classifier 
- Naive Bayes: GaussianNB
- K-Nearest Neighbors (KNN) >
- Neural Networks like Multi-Layer Perceptron






Regression models are not suitable for single-label multi-class classification problems. Regression models are designed to predict continuous numerical values, whereas single-label multi-class classification involves predicting one label from a set of discrete classes.

In [2]:
from sklearn.multioutput import MultiOutputClassifier,MultiOutputRegressor


In [3]:
import pandas as pd #Pandas is for Data processing. 
import numpy as np #Numpy is for numerical calculations.
import matplotlib.pyplot as plt #plotting and visually understanding the data.
from sklearn.preprocessing import LabelEncoder #converts things like "monsoon", "summer" into numeric labels like 0 1 2
import pandas as pd #Pandas is for Data processing. 
import numpy as np #Numpy is for numerical calculations.
import matplotlib.pyplot as plt #plotting and visually understanding the data.
from sklearn.model_selection import train_test_split #split the data into testing and training set
from sklearn.preprocessing import LabelEncoder #converts things like "monsoon", "summer" into numeric labels like 0 1 2
from sklearn.multioutput import MultiOutputClassifier
# Preprocessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, PolynomialFeatures

# Feature Selection
from sklearn.feature_selection import SelectKBest, RFE, SelectFromModel


In [4]:

# Linear models
from sklearn.linear_model import  Ridge, Lasso, ElasticNet, LogisticRegression, LinearRegression
# Tree-based models
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
# Ensemble modelsx
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, GradientBoostingClassifier, GradientBoostingRegressor, AdaBoostClassifier, AdaBoostRegressor
# Support Vector Machines
from sklearn.svm import SVC, SVR
# Neighbors
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
# Naive Bayes
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

# Clustering
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN

# Decomposition
from sklearn.decomposition import PCA, NMF

# Neural Network
from sklearn.neural_network import MLPClassifier, MLPRegressor

# Discriminant Analysis
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis

# Gaussian Processes
from sklearn.gaussian_process import GaussianProcessClassifier, GaussianProcessRegressor

# Model Selection
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

# Metrics
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score, confusion_matrix, classification_report

# Pipeline
from sklearn.pipeline import Pipeline


In [5]:
df = pd.read_csv("lil_data.csv")
display(df)

bodysite  disease       age  gender   country       bmi  infant_gender  \
0    0.791667       17  0.268657     0.6  0.055556  0.621374            1.0   
1    0.041667        9  1.000000     0.4  0.944444  1.000000            1.0   
2    0.541667        9  1.000000     0.4  0.944444  1.000000            1.0   
3    0.791667        9  0.109453     0.4  0.888889  1.000000            1.0   
4    0.791667        9  1.000000     0.4  0.944444  1.000000            1.0   
..        ...      ...       ...     ...       ...       ...            ...   
995  0.041667        9  1.000000     0.4  0.944444  1.000000            1.0   
996  0.000000        9  1.000000     0.6  0.944444  1.000000            1.0   
997  0.541667        9  1.000000     0.4  0.944444  1.000000            1.0   
998  0.791667        9  1.000000     0.6  0.555556  1.000000            1.0   
999  0.000000        9  1.000000     0.6  0.944444  1.000000            1.0   

     collectionweek  samplecollectionwindow  delivery_mode  ...  \
0          0.428571                     1.0            0.5  ...   
1          0.428571                     1.0            0.5  ...   
2          0.428571                     1.0            0.5  ...   
3          0.428571                     1.0            0.5  ...   
4          0.428571                     1.0            0.5  ...   
..              ...                     ...            ...  ...   
995        0.428571                     1.0            0.5  ...   
996        0.428571                     1.0            0.5  ...   
997        0.428571                     1.0            0.5  ...   
998        0.428571                     1.0            0.5  ...   
999        0.428571                     1.0            0.5  ...   

     k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Enterococcaceae|g__Enterococcus|s__Enterococcus_gilvus|t__Enterococcus_gilvus_unclassified  \
0                                                  0.0                                                                                                       
1                                                  0.0                                                                                                       
2                                                  0.0                                                                                                       
3                                                  0.0                                                                                                       
4                                                  0.0                                                                                                       
..                                                 ...                                                                                                       
995                                                0.0                                                                                                       
996                                                0.0                                                                                                       
997                                                0.0                                                                                                       
998                                                0.0                                                                                                       
999                                                0.0                                                                                                       

     k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae|g__Lactobacillus|s__Lactobacillus_otakiensis  \
0                                                  0.0                                                                          
1                                                  0.0                                          

Data Splitting:

In [6]:
Input_Features = [col for col in df.columns if col != 'disease']
X = df[Input_Features]
Y = df['disease']
# Splitting the data into training and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# 1. Multi-Class Classifiation using SVM

for this, we will be using the One-vs-Rest strategy. In this strategy, we fit one classifier per class. For each classifier, we assign the class as the positive class and all other classes as the negative class. We then predict the class with the highest confidence score.

In [7]:
from sklearn.multiclass import OneVsRestClassifier
basemodel = SVC()
model = OneVsRestClassifier(basemodel)
model.fit(X_train, Y_train)
Y_predORSVC = model.predict(X_test)
print('Accuracy: ', accuracy_score(Y_test, Y_predORSVC))
print('Confusion Matrix: ', confusion_matrix(Y_test, Y_predORSVC))
print('Classification Report: ', classification_report(Y_test, Y_predORSVC))

Accuracy:  0.765
Confusion Matrix:  [[  0   0   0   0   0   0   3   0   0   0   0   0   0   0]
 [  0   6   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   1   0   0   0   8   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   2   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   6   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0 113   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   1  27   0   0   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   9   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   5   0   0]
 [  0   0   0   2   0   0   9   0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   3   0   0   0   0   0   0   0]]
Classification Report:                precision    recall  f1-score   support

           2       0.00      0.00      0.00         3
    

C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

# 2. Logistic Regression
Here also we will be using One-vs-Rest strategy.
>One might ask: "why are we using regression here when we are dealing with classification problem?" The answer is that logistic regression is a classification algorithm. The name "regression" in logistic regression is a misnomer. Logistic regression is a classification algorithm that predicts the probability of an instance belonging to a particular class.

In [8]:
modelLR = LogisticRegression()
multimodelLR = MultiOutputRegressor(modelLR)
multimodelLR.fit(X_train, Y_train.values.reshape(-1, 1))
Y_predLR = multimodelLR.predict(X_test).reshape(-1)
print("Accuracy: ", accuracy_score(Y_test, Y_predLR))
print("Confusion Matrix: \n", confusion_matrix(Y_test, Y_predLR))
print("Classification Report: \n", classification_report(Y_test, Y_predLR))


Accuracy:  0.89
Confusion Matrix: 
 [[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   2   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   6   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   8   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   2   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   5   0   0   0   1   0   0   0   0]
 [  1   0   0   0   2   0   1 104   0   0   4   1   0   1   0]
 [  0   0   0   0   0   0   0   1  27   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   8   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   5   0   0]
 [  0   0   0   0   2   0   0   0   0   0   0   0   0  10   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0   0   0   2]]
Classification Rep

C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: R

# 3. Decision Tree Classifier

In [9]:
modelDTC = DecisionTreeClassifier()
modelDTC.fit(X_train, Y_train)
Y_predDTC = modelDTC.predict(X_test)
print("Accuracy: ", accuracy_score(Y_test, Y_predDTC))
print("Confusion Matrix: \n", confusion_matrix(Y_test, Y_predDTC))
print("Classification Report: \n", classification_report(Y_test, Y_predDTC))

Accuracy:  0.905
Confusion Matrix: 
 [[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   3   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   6   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   5   0   0   0   3   1   0   0   0   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0   0   0   0   0   1   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   0   6   0   0   0   0   0   0   0   0   0   0]
 [  1   0   0   3   3   1   0 106   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  28   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   9   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   

C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

# 4. KNN Classifier

In [10]:
modelKNNC = KNeighborsClassifier()
modelKNNC.fit(X_train,Y_train)
predictKNNC = modelKNNC.predict(X_test)
print("Accuracy: \n", accuracy_score(Y_test, predictKNNC))
print("Confusion Matrix: \n", confusion_matrix(Y_test, predictKNNC))
print(classification_report(Y_test, predictKNNC))  


Accuracy: 
 0.855
Confusion Matrix: 
 [[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   3   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   6   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   9   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   2   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   5   0   0   0   1   0   0   0   0]
 [  1   1   0   0   4   0   4 101   0   0   3   0   0   0   0]
 [  0   0   0   0   0   0   0   1  27   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   4   0   0   0   5   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   5   0   0]
 [  0   0   0   0   1   0   0   5   0   0   0   0   0   6   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   3]]
              pr

C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

# 5. Random forest classifier

In [11]:
modelRT = RandomForestClassifier()
modelRT.fit(X_train, Y_train)
Y_predRT = modelRT.predict(X_test)
print("Accuracy: ", accuracy_score(Y_test, Y_predRT))
print("Confusion Matrix: \n", confusion_matrix(Y_test, Y_predRT))
print("Classification Report: \n", classification_report(Y_test, Y_predRT))

Accuracy:  0.81
Confusion Matrix: 
 [[  0   0   0   0   0   0   3   0   0   0   0   0   0   0]
 [  0   5   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   5   0   0   0   4   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   2   4   0   0   0   0   0   0   0]
 [  0   0   0   2   0   2 109   0   0   1   0   0   0   0]
 [  0   0   0   0   0   0   1  27   0   0   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   6   0   0   3   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   5   0   0]
 [  0   0   0   1   0   0   7   0   0   0   0   0   4   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   0   2]]
Classification Report: 
               precision    recall  f1-score   support

           2       0.00      0.00      0.00         3
   

C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

# 7. Naive Bayes: GaussianNB

In [14]:
ModelNBGNB = GaussianNB()
ModelNBGNB.fit(X_train, Y_train)
Y_predGNB = ModelNBGNB.predict(X_test)
print("Accuracy: ", accuracy_score(Y_test, Y_predGNB))
print("Confusion Matrix: \n", confusion_matrix(Y_test, Y_predGNB))
print("Classification Report: \n", classification_report(Y_test, Y_predGNB))


Accuracy:  0.745
Confusion Matrix: 
 [[  0   0   0   0   0   0   3   0   0   0   0   0   0   0]
 [  0   3   0   0   0   0   3   0   0   0   0   0   0   0]
 [  0   0   4   0   0   0   5   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   2   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   5   0   0   0   0   0   1   0]
 [  0   0   0   0   0   0 104   0   0   3   0   0   7   0]
 [  0   0   0   0   0   0   0  28   0   0   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   2   2   0   0   4   0   0   1   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   5   0   0]
 [  0   0   0   0   0   0  11   0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   3   0   0   0   0   0   0   0]]
Classification Report: 
               precision    recall  f1-score   support

           2       0.00      0.00      0.00         3
  

C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

# 8. MLP for Classification

In [15]:
ModelMLP = MLPClassifier()
ModelMLP.fit(X_train, Y_train)
Y_predMLP = ModelMLP.predict(X_test)
print("Accuracy: ", accuracy_score(Y_test, Y_predMLP))
print("Confusion Matrix: \n", confusion_matrix(Y_test, Y_predMLP))
print("Classification Report: \n", classification_report(Y_test, Y_predMLP))


Accuracy:  0.815
Confusion Matrix: 
 [[  1   0   0   0   0   0   2   0   0   0   0   0   0   0]
 [  0   5   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   7   0   0   0   2   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   2   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0]
 [  0   0   0   0   0   5   0   0   0   1   0   0   0   0]
 [  0   0   0   1   0   3 102   1   0   3   0   0   4   0]
 [  0   0   0   0   0   0   0  28   0   0   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   2   5   0   0   2   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   5   0   0]
 [  0   0   0   2   0   0   4   0   0   0   0   0   6   0]
 [  0   0   0   0   0   0   2   0   0   0   0   0   0   1]]
Classification Report: 
               precision    recall  f1-score   support

           2       1.00      0.33      0.50         3
  

C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\satya\AppData\Roaming\Python\Python313\site-packages\sklearn\m

# 6(2). XGBOOST
XGBoost is a powerful tool for classification tasks, including single-label multi-class classification, and it often provides high accuracy and efficiency

In [ ]:
from xgboost import XGBClassifier

modelXBGBOOST = XGBClassifier()
modelXBGBOOST.fit(X_train, Y_train)
Y_predXBGBOOST = modelXBGBOOST.predict(X_test)
print("Accuracy: ", accuracy_score(Y_test, Y_predXBGBOOST))
print("Confusion Matrix: \n", confusion_matrix(Y_test, Y_predXBGBOOST))
print("Classification Report: \n", classification_report(Y_test, Y_predXBGBOOST))


NOTE : GRADIENT BOOSTING CLASSIFIER AND XGBOOST ARE EXTREMELY TIME CONSUMING
# 6. Gradient Boosting Classifier

In [13]:
ModelGBC = GradientBoostingClassifier()
ModelGBC.fit(X_train, Y_train)
Y_predGBC = ModelGBC.predict(X_test)
print("Accuracy: ", accuracy_score(Y_test, Y_predGBC))
print("Confusion Matrix: \n", confusion_matrix(Y_test, Y_predGBC))
print("Classification Report: \n", classification_report(Y_test, Y_predGBC))

KeyboardInterrupt: 